const p3 = document.querySelector(".p3");
const p2 = document.querySelector(".p2");

function changeColorP3() {
  p3.style.backgroundColor = "lightblue";
}
// Function change color of P2
function changeColorP2() {
  p2.style.backgroundColor = "lightblue";
}
// Call changeColorP2 Function OnClick
p2.onclick = changeColorP2;
// Define document root for function below
const p4 = document.querySelector("section#b p");
p4.addEventListener("click", function () {
  const ul = document.querySelector("section#b ul");
  const newLi = document.createElement("li");
  const newLiText = document.createTextNode("This new Li generated by Js");
  newLi.appendChild(newLiText);
  ul.appendChild(newLi);
});

// Event Mouse Enter and Mouse Leave
p3.addEventListener("mouseenter", function () {
  p3.style.backgroundColor = "lightblue";
});
p3.addEventListener("mouseleave", function () {
  p3.style.backgroundColor = "white";
});
/*
  / Event OnClick akan mengabaikan dan merubah event yang tersedia
  / Sedangkan Even addEventListener tidak merubah, tetapi menambah
*/
